export const ADD = 'ADD'
export const REMOVE = 'REMOVE'
export const CLEAR = 'CLEAR'
export const INC = 'INC'
export const DEC = 'DEC'
export const ADD_PRICE = 'ADD_PRICE'
export const REMOVE_PRICE = 'REMOVE_PRICE'